// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW5b8adeo0wYbSSYpOm3cIYw9k1YZqFmA',
    appId: '1:705587892382:web:f90c337b0c2a750d086b8f',
    messagingSenderId: '705587892382',
    projectId: 'movie-list-1eba1',
    authDomain: 'movie-list-1eba1.firebaseapp.com',
    storageBucket: 'movie-list-1eba1.appspot.com',
    measurementId: 'G-DQKQK5K7JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDo2Byt6tJ4ZNXZxnfW15tpDiRjdJj_Q',
    appId: '1:705587892382:android:959ad77be177b6dd086b8f',
    messagingSenderId: '705587892382',
    projectId: 'movie-list-1eba1',
    storageBucket: 'movie-list-1eba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknMRWa82v4TpoccO6J0OqQziVR1R-jXE',
    appId: '1:705587892382:ios:31fabd4dba9c48dd086b8f',
    messagingSenderId: '705587892382',
    projectId: 'movie-list-1eba1',
    storageBucket: 'movie-list-1eba1.appspot.com',
    iosBundleId: 'com.example.uasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknMRWa82v4TpoccO6J0OqQziVR1R-jXE',
    appId: '1:705587892382:ios:e82ef2a427dd6554086b8f',
    messagingSenderId: '705587892382',
    projectId: 'movie-list-1eba1',
    storageBucket: 'movie-list-1eba1.appspot.com',
    iosBundleId: 'com.example.uasApp.RunnerTests',
  );
}
